name: build windows
on: push

jobs:
  job1:
    runs-on: windows-latest
    env:
      MIDIEDITOR_RELEASE_VERSION_STRING: "\"continuous integration triggered by ${{ github.sha }}\""
      MIDIEDITOR_RELEASE_DATE: "%DATE%"
    if: always()
    strategy:
      matrix:
        include:
          - qt_ver: 5.15.2
            qt_arch: win64_msvc2019_64
            msvc_arch: x64
            qt_arch_install: msvc2019_64
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
          host: 'windows'
          target: 'desktop'
          cached: 'false'

      - uses: jmarrec/setup-qtifw@v1
        with:
          qtifw-version: '4.x'
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup Visual Studio environment
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.msvc_arch }}

      - name: Build with qmake and nmake
        shell: cmd
        run: |
          set MIDIEDITOR_RELEASE_DATE="%DATE%"
          qmake
          nmake

      - name: Copy Files 
        shell: pwsh
        run: |
          mkdir ./packaging/org.midieditor.midieditor/data/
          cp ./bin/ProMidEdit.exe ./packaging/org.midieditor.midieditor/data/ProMidEdit.exe
          windeployqt ./packaging/org.midieditor.midieditor/data/ProMidEdit.exe
          mkdir ./packaging/org.midieditor.midieditor/data/metronome
          cp ./run_environment/metronome/metronome-01.wav ./packaging/org.midieditor.midieditor/data/metronome
          mkdir ./packaging/org.midieditor.manual/data/
          cp -Recurse -Path ./...
