name: build windows
on: push

jobs:
  job1:
    runs-on: windows-latest
    env:
      MIDIEDITOR_RELEASE_VERSION_STRING: continous integration triggerd by {{ github.sha }}
    if: always()
    strategy:
      # 矩阵配置
      matrix:
        include:
          # 5.9.9 参考 https://mirrors.cloud.tencent.com/qt/online/qtsdkrepository/windows_x86/desktop/qt5_599/
          - qt_ver: 5.9.9
            qt_arch: win32_msvc2015
            msvc_arch: x86
            qt_arch_install: msvc2015
          - qt_ver: 5.9.9
            qt_arch: win64_msvc2017_64
            msvc_arch: x64
            qt_arch_install: msvc2017_64
          # 5.12.10 参考 https://mirrors.cloud.tencent.com/qt/online/qtsdkrepository/windows_x86/desktop/qt5_51210/            
          - qt_ver: 5.12.10
            qt_arch: win32_msvc2017
            msvc_arch: x86
            qt_arch_install: msvc2017
          - qt_ver: 5.12.10            
            qt_arch: win64_msvc2017_64
            msvc_arch: x64
            qt_arch_install: msvc2017_64
          # 5.15.2 参考 https://mirrors.cloud.tencent.com/qt/online/qtsdkrepository/windows_x86/desktop/qt5_5152/
          - qt_ver: 5.15.2
            qt_arch: win32_msvc2019
            msvc_arch: x86
            qt_arch_install: msvc2019
          - qt_ver: 5.15.2          
            qt_arch: win64_msvc2019_64
            msvc_arch: x64
            qt_arch_install: msvc2019_64          
          # 6.0.0 Due to Qt API change, no support for qt 6.0
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
          host: 'windows'
          target: 'desktop'
          cached: 'false'
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: msvc-build
        id: build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.msvc_arch }}
          qmake
          nmake
          cp ./bin/ProMidEdit.exe ./packaging/ProMidEdit.exe
      - name: Upload 
        uses: actions/upload-artifact@v2
        with:
          name: midieditor
          path: |
            packaging/ProMidEdit.exe
            packaging/metronome/
      - name: Report 
          echo winSdkDir=%WindowsSdkDir% >> %GITHUB_ENV%
          echo winSdkVer=%WindowsSdkVersion% >> %GITHUB_ENV%
          echo vcToolsInstallDir=%VCToolsInstallDir% >> %GITHUB_ENV%
          echo vcToolsRedistDir=%VCToolsRedistDir% >> %GITHUB_ENV%