name: build windows
on: push

jobs:
  job1:
    runs-on: windows-latest
    env:
      MIDIEDITOR_RELEASE_VERSION_STRING: "\"continous integration triggerd by ${{ github.sha }}\""
      MIDIEDITOR_RELEASE_DATE: ""
    if: always()
    strategy:
      # 矩阵配置
      matrix:
        include:
          # 5.9.9 参考 https://mirrors.cloud.tencent.com/qt/online/qtsdkrepository/windows_x86/desktop/qt5_599/
          - qt_ver: 5.9.9
            qt_arch: win32_msvc2015
            msvc_arch: x86
            qt_arch_install: msvc2015
          - qt_ver: 5.9.9
            qt_arch: win64_msvc2017_64
            msvc_arch: x64
            qt_arch_install: msvc2017_64
          # 5.12.10 参考 https://mirrors.cloud.tencent.com/qt/online/qtsdkrepository/windows_x86/desktop/qt5_51210/            
          - qt_ver: 5.12.10
            qt_arch: win32_msvc2017
            msvc_arch: x86
            qt_arch_install: msvc2017
          - qt_ver: 5.12.10            
            qt_arch: win64_msvc2017_64
            msvc_arch: x64
            qt_arch_install: msvc2017_64
          # 5.15.2 参考 https://mirrors.cloud.tencent.com/qt/online/qtsdkrepository/windows_x86/desktop/qt5_5152/
          - qt_ver: 5.15.2
            qt_arch: win32_msvc2019
            msvc_arch: x86
            qt_arch_install: msvc2019
          - qt_ver: 5.15.2          
            qt_arch: win64_msvc2019_64
            msvc_arch: x64
            qt_arch_install: msvc2019_64          
          # 6.0.0 Due to Qt API change, no support for qt 6.0
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
          host: 'windows'
          target: 'desktop'
          cached: 'false'

      - uses: jmarrec/setup-qtifw@v1
        with:
          qtifw-version: '4.x' # Version range or exact version of a QtIFW version to use, using SemVer's version range syntax
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true

      - name: msvc-build
        id: build
        shell: cmd
        run: |
          set MIDIEDITOR_RELEASE_DATE="%DATE%"
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.msvc_arch }}
          qmake
          nmake
      - name: Copy Files 
        shell: pwsh
        run: |
          mkdir ./packaging/org.midieditor.midieditor/data/
          cp ./bin/ProMidEdit.exe ./packaging/org.midieditor.midieditor/data/ProMidEdit.exe
          windeployqt ./packaging/org.midieditor.midieditor/data/ProMidEdit.exe
          mkdir ./packaging/org.midieditor.midieditor/data/metronome
          cp ./run_environment/metronome/metronome-01.wav ./packaging/org.midieditor.midieditor/data/metronome
          mkdir ./packaging/org.midieditor.manual/data/
          cp -Recurse -Path ./manual/ -Destination ./packaging/org.midieditor.manual/data/
      - name: packaging
        shell: cmd
        run: |
          binarycreator.exe --offline-only -c .\scripts\packaging\windows\config.xml -p .\packaging Install.exe
      - name: Upload 
        uses: actions/upload-artifact@v2
        with:
          name: midieditor-${{ matrix.qt_ver }}-${{ matrix.qt_arch }}
          path: |
            Install.exe
      - name: Report 
        shell: cmd
        run: |
          echo winSdkDir=%WindowsSdkDir% >> %GITHUB_ENV%
          echo winSdkVer=%WindowsSdkVersion% >> %GITHUB_ENV%
          echo vcToolsInstallDir=%VCToolsInstallDir% >> %GITHUB_ENV%
          echo vcToolsRedistDir=%VCToolsRedistDir% >> %GITHUB_ENV%