name: build with xmake on windows
on: push

jobs:
  build:
    runs-on: windows-latest
    if: always()
    steps:
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.8.2
      - name: update repo
        run: |
          xrepo update-repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: cache packages from xrepo
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
          key: ${{ runner.os }}-xrepo-qt-${{ hashFiles('scripts/xmake/packages.lua') }}
      - name: cache xmake
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/.xmake/**/cache
            ${{ github.workspace }}/build/.build_cache
            ${{ github.workspace }}/build/.deps
            ${{ github.workspace }}/build/.gens
            ${{ github.workspace }}/build/.objs
          key: ${{ runner.os }}-xmake-build-${{ hashFiles('**/xmake.lua') }}

      - name: config by xmake
        run: |
          xmake config --yes

      - name: build by xmake
        run: |
          xmake build --jobs=2

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ProMidEdit
          path: build/windows/x64/release/ProMidEdit.exe
